site_name: UGS
theme: cosmo
repo_url: https://github.com/winder/Universal-G-Code-Sender
site_author: Will Winder
site_description: "Cross platform G-Code sender with advanced features for GRBL based CNC machines."

pages:
- 'Home': 'index.md'
- 'Download': 'download.md'
- 'User Guide':
    - "UGS Platform": 'guide/platform.md'
    - "Setup": 'guide/user.md'
- 'Developer Guide':
    - "Getting Started": 'dev/getting_started.md'
    - "Backend": 'dev/development.md'
    - "Plugin": 'dev/plugin.md'
- 'Contributing':
    - "Code" : 'contrib/code.md'
    - "Translations": 'contrib/translation.md'
    - "Donating": 'contrib/donation.md'

