site_name: UGS
theme: cosmo
repo_url: https://github.com/winder/Universal-G-Code-Sender
site_author: Will Winder
site_description: "Cross platform G-Code sender with advanced features for GRBL based CNC machines."

pages:
- 'Home': 'index.md'
- 'Download': 'download.md'
- 'Docs':
    - "User": 'guide/user.md'
    - "Developer": 'guide/developer.md'
    - "Plugin": 'guide/plugin.md'
- 'Contributing':
    - "Code": 'contrib/development.md'
    - "Translations": 'contrib/translation.md'
    - "Donating": 'contrib/donation.md'
